services:
  web:
    build: ./
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=DAG_db
      - DB_USER=user
      - DB_PASSWORD=1357920_user
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1357920_egor
      - POSTGRES_DB=DAG_db
    volumes:
      - ./01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres -d DAG_db" ]
        interval: 5s
        timeout: 5s
        retries: 5
    ports:
      - "5432:5432"

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=DAG_db
      - DB_USER=postgres
      - DB_PASSWORD=1357920_egor
      - API_URL=http://web:8080
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    depends_on:
      web:
        condition: service_started
      db:
        condition: service_healthy

volumes:
  postgres_data:
